version: '3'

services:

  grpc-server:
    container_name: grpc-server
    build: ./../build
    tty: true
    ports:
      - 3000:3000
    working_dir: /usr/src/app/pkg/server/main
    volumes:
      - ./../:/usr/src/app
    environment:
      SERVICE_URL: "http://localhost:3000"

  grpc-client:
    container_name: grpc-client
    build: ./../build
    tty: true
    ports:
      - 3001:3001
    working_dir: /usr/src/app/pkg/client/main
#    command: /bin/sh -c "apk update && apk add protoc && go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && go mod tidy"
    volumes:
      - ./../:/usr/src/app
    environment:
      SERVICE_URL: "http://localhost:3001"